//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.235
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lofinil.GameSDK.Editor.SharedRes {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lofinil.GameSDK.Editor.SharedRes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _16_CompDelete {
            get {
                object obj = ResourceManager.GetObject("_16_CompDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_CompEdit {
            get {
                object obj = ResourceManager.GetObject("_16_CompEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_CompGo {
            get {
                object obj = ResourceManager.GetObject("_16_CompGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_Compink {
            get {
                object obj = ResourceManager.GetObject("_16_Compink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_CompNew {
            get {
                object obj = ResourceManager.GetObject("_16_CompNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_Form {
            get {
                object obj = ResourceManager.GetObject("_16_Form", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_New {
            get {
                object obj = ResourceManager.GetObject("_16_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_Nonvisible {
            get {
                object obj = ResourceManager.GetObject("_16_Nonvisible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_Table {
            get {
                object obj = ResourceManager.GetObject("_16_Table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_Trigger {
            get {
                object obj = ResourceManager.GetObject("_16_Trigger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_Visible {
            get {
                object obj = ResourceManager.GetObject("_16_Visible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_ZoomIn {
            get {
                object obj = ResourceManager.GetObject("_16_ZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _16_ZoomOut {
            get {
                object obj = ResourceManager.GetObject("_16_ZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_AlignHC {
            get {
                object obj = ResourceManager.GetObject("_22_AlignHC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_AlignHL {
            get {
                object obj = ResourceManager.GetObject("_22_AlignHL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_AlignHR {
            get {
                object obj = ResourceManager.GetObject("_22_AlignHR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_AlignVB {
            get {
                object obj = ResourceManager.GetObject("_22_AlignVB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_AlignVC {
            get {
                object obj = ResourceManager.GetObject("_22_AlignVC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_AlignVT {
            get {
                object obj = ResourceManager.GetObject("_22_AlignVT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Anim {
            get {
                object obj = ResourceManager.GetObject("_22_Anim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Block {
            get {
                object obj = ResourceManager.GetObject("_22_Block", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Bottom {
            get {
                object obj = ResourceManager.GetObject("_22_Bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Color {
            get {
                object obj = ResourceManager.GetObject("_22_Color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Config {
            get {
                object obj = ResourceManager.GetObject("_22_Config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Copy {
            get {
                object obj = ResourceManager.GetObject("_22_Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Create {
            get {
                object obj = ResourceManager.GetObject("_22_Create", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Delete {
            get {
                object obj = ResourceManager.GetObject("_22_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Down {
            get {
                object obj = ResourceManager.GetObject("_22_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Filter {
            get {
                object obj = ResourceManager.GetObject("_22_Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_FreeCamera {
            get {
                object obj = ResourceManager.GetObject("_22_FreeCamera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Library {
            get {
                object obj = ResourceManager.GetObject("_22_Library", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Move {
            get {
                object obj = ResourceManager.GetObject("_22_Move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Movie {
            get {
                object obj = ResourceManager.GetObject("_22_Movie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Picker {
            get {
                object obj = ResourceManager.GetObject("_22_Picker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Resize {
            get {
                object obj = ResourceManager.GetObject("_22_Resize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Rotate {
            get {
                object obj = ResourceManager.GetObject("_22_Rotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Rotate2 {
            get {
                object obj = ResourceManager.GetObject("_22_Rotate2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Save {
            get {
                object obj = ResourceManager.GetObject("_22_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Scale {
            get {
                object obj = ResourceManager.GetObject("_22_Scale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Select {
            get {
                object obj = ResourceManager.GetObject("_22_Select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Top {
            get {
                object obj = ResourceManager.GetObject("_22_Top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Up {
            get {
                object obj = ResourceManager.GetObject("_22_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _22_Wizard {
            get {
                object obj = ResourceManager.GetObject("_22_Wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Origin {
            get {
                object obj = ResourceManager.GetObject("Origin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ResizeControl {
            get {
                object obj = ResourceManager.GetObject("ResizeControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ResizeHLine {
            get {
                object obj = ResourceManager.GetObject("ResizeHLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ResizeVLine {
            get {
                object obj = ResourceManager.GetObject("ResizeVLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Rounded_BL {
            get {
                object obj = ResourceManager.GetObject("Rounded_BL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Rounded_BR {
            get {
                object obj = ResourceManager.GetObject("Rounded_BR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Rounded_TL {
            get {
                object obj = ResourceManager.GetObject("Rounded_TL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Rounded_TR {
            get {
                object obj = ResourceManager.GetObject("Rounded_TR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SystemH {
            get {
                object obj = ResourceManager.GetObject("SystemH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SystemH5 {
            get {
                object obj = ResourceManager.GetObject("SystemH5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SystemV {
            get {
                object obj = ResourceManager.GetObject("SystemV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SystemV5 {
            get {
                object obj = ResourceManager.GetObject("SystemV5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap White {
            get {
                object obj = ResourceManager.GetObject("White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
